### ISSUE TITLE
DeveloperApp.init is returning undefined "authorization" property

### ISSUE THREAD

**Issue by hah-dev-team** [livechat/developer-sdk#2]
**Describe the bug**
I can't authenticate/authorize using the developer-sdk.

**To Reproduce**

1. Call DeveloperApp.init(...) passing the config object containing App ID and Client ID.

**Expected behavior**
To receive a valid response.

**Screenshots**
![image](https://github.com/livechat/developer-sdk/assets/146973811/7d8e8d6b-d5c5-4fc9-82f5-15aa7aa5e326)

**Desktop (please complete the following information):**

- OS: Windows
- Node.js version: 18.18.2

**Additional context**

**Comment by wojciechdudek-text** [comment]
Hi,

We have already addressed a small issue in the @livechat/developer-sdk. Please ensure that you have downloaded the latest version (v1.3.63).

Two questions:
1. Have you built your application based on our sample app or repository templates? You can find them here: https://platform.text.com/console/apps/explore/sample-apps
2. Have you verified whether the redirect URL in the authorization block is configured correctly for your application URL?

**Comment by hah-dev-team** [comment]
Hi Wojciech

I tried using the v.1.3.63 but I’m still getting an undefined response from the app.authorize() method.

Have you built your application based on our sample app or repository templates? You can find them here: https://platform.text.com/console/apps/explore/sample-apps

Yes.

Have you verified whether the redirect URL in the authorization block is configured correctly for your application URL?

Yes. It was working intermittently with the same settings but now it’s just not working.
For development purposes currently the authorization block is pointing to my localhost only.

Thanks,
Gustavo Contreiras

**Comment by wojciechdudek-text** [comment]
Which authorization strategy do you use in your app? In the documentation, we mentioned that the authorize method can return undefined for the redirect strategy, but only when it is called initially. After a successful login and redirection back to your app, the authorize method should be called once again, but this time it should return authorization data.

![image](https://github.com/livechat/developer-sdk/assets/117641044/44f636e6-aaa3-450c-a57d-d4077a902f16)

If you are using our template, please also have a look at latest react example:

https://www.npmjs.com/package/@livechat/developer-sdk#in-react

**Comment by hah-dev-team** [comment]
There are so many different documents sources that sometimes I’m not sure where to check for things.

Anyway… If I choose the “popup” method, it still doesn’t work.

It opens a popup with this URL and quickly closes it: https://accounts.livechat.com/ooops?client_id=54527e6c6b274e30f348a0e25566cc05&exception_details=the+server+encountered+an+unexpected+condition+that+prevented+it+from+fulfilling+the+request&flow=button&oauth_exception=invalid_request&redirect_uri=https%3A%2F%2Flocalhost%3A3001%2Flivechat%2Fchat-details&request_id=7b7034ae-645c-4415-9e4f-67928bd5a5d2&response_type=token&utm_medium=accounts-sdk&utm_source=accounts.livechat.com

Inspecting the URL I can see that “the server encountered an unexpected condition”.

And if I choose “iframe” method it just keeps hanging in a white screen.

**Comment by wojciechdudek-text** [comment]
> There are so many different documents sources that sometimes I’m not sure where to check for things.

I see what you mean.

Anyway, it still looks like configuration issue. Please check authorization block once again - redirect URI should contain valid protocol and port. If your application is running locally on `https://localhost:3000`, then redirect uri should look like: `https://localhost:3000`. 

Docs reference: https://platform.text.com/docs/authorization/authorizing-api-calls/#examples
